### ISSUE TITLE
Need to fill out 'Description of Logged Events' on Project Sidewalk wiki

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/sidewalk-quality-analysis#13] opened 2019-06-17 13:38 UTC
We need to fill out need to fill out 'Description of Logged Events' on Project Sidewalk wiki: https://github.com/ProjectSidewalk/SidewalkWebpage/wiki/Descriptions-of-Logged-Events

Will be a good task for @daotyl000 and @nchowder to work together. Obviously, since they didn't write the logger, they will likely need to communicate with @misaugstad and other folks on the PS Slack.

**Comment by daotyl000** [comment] 2019-08-13 23:20
duplicate of issue #6

**Closed by daotyl000** 2019-08-13 23:20 UTC
